name: Protect main branch

on:
  pull_request:
    branches:
      - main

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Block merge if not from develop
        if: github.head_ref != 'develop'
        run: |
          echo "PRs para main só são permitidos a partir da branch develop."
          echo "Branch de origem: ${{ github.head_ref }}"
          exit 1

      - name: OK
        run: echo "Branch de origem válida: develop"
